import Head from 'next/head'
import {WiMoonAltThirdQuarter} from 'react-icons/wi';
import {AiOutlineLinkedin, AiOutlineGithub, AiOutlineMail} from 'react-icons/ai';
import Image from "next/image";
import profile from "../public/profile.PNG"
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jan Arvik Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white dark:bg-gray-800 h-screen w-screen'> 
        <section className='bg-white dark:bg-gray-800'>
          <nav className='p-10 mb-12 flex justify-between'>
            <h1 className='font-courierBold text-xl text-black dark:text-white'>&gt; Jan Arvik</h1>
            <ul className='flex items-center'>
              <li>
                <WiMoonAltThirdQuarter onClick={() => setDarkMode(!darkMode)} 
                className='cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li><a className='hover:bg-slate-700 font-courier bg-slate-500 text-white px-4
              py-2 rounded-md ml-8 dark:bg-slate-900 dark:hover:bg-slate-600' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='font-courier text-start max-w-md m-auto px-3 py-0'>
            <div className='flex justify-around'>
              <div className='py-12'>
              <h2 className='text-3xl text-green-900 font-medium dark:text-green-300'>Jan Arvik</h2>
              <h3 className='text-xl text-black dark:text-white'>Student and Developer</h3>
              </div>
            <Image src={profile} className= 'relative mx-auto w-40 h-40 rounded-full overflow-hidden p-2'/>
            </div>
            <p className='text-start text-sm text-gray-800 dark:text-slate-300 py-2'>
            Current student working toward Bachelor in Computer Science, seeking an opportunity to begin a career.
            Identifies and quickly closes any knowledge gaps to offer value to employer and team. Willing to take
            on any task to support team and help business succeed. Offers strong programming and management abilities.
            </p>
          </div>
          <div className='text-3xl flex justify-center text-gray-600 gap-16 py-3 dark:text-white'>
          <a href="https://www.linkedin.com/in/jantarvik">
            <AiOutlineLinkedin className='hover:scale-105'/>
          </a>
          <a href="https://github.com/Skumbl">
            <AiOutlineGithub className='hover:scale-105'/>
          </a>
          <a href="mailto: janarvik01@vt.edu">
            <AiOutlineMail className='hover:scale-105'/>
          </a>
          </div>
        </section> 
        <section className="bg-white dark:bg-gray-800 font-courierBold">
          <div className=' text-md max-w-md m-auto px-3 text-black dark:text-white'>
            <h3 className='text-lg'>&gt; work experience</h3>

            <div className='grid grid-cols-4 text-sm font-courier text-start'>
              <div className='col-span-1 py-1'>2022</div>
              <div className='col-span-3 py-1'> <span className='text-gray-500'>ID Tech</span> 
              <p>instructed highschoolers in java script, C#, and object-oriented programming</p>
              </div>
              <div className='col-span-1 py-1'>2020</div>
              <div className='col-span-3 py-1'> <span className='text-gray-500'>AWS</span> 
              <p>maintained and repaired AWS server infastructure, hardware troubleshooting and diagnostics</p>
              </div>
            </div>

          </div>
        </section>
        <section>
          <div className='py-10 bg-white dark:bg-gray-800'>

          </div>
        </section>
      </main>
    </div>
  )
}