import Head from 'next/head'
import {WiMoonAltThirdQuarter} from 'react-icons/wi';
import {AiOutlineLinkedin, AiOutlineGithub, AiOutlineMail} from 'react-icons/ai';
import Image from "next/image";
import profile from "../public/profile.PNG"
import { useState } from 'react';
import Link from 'next/link';


export default function Home() {
    const [darkMode, setDarkMode] = useState(true);
    return (
    <div className={darkMode ? "dark" : ""}>
    <Head>
        <title>Jan Arvik Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>


    <main className='bg-white dark:bg-gray-800 h-screen w-screen'> 
    <section className='bg-white dark:bg-gray-800'>
      <nav className='p-10 mb-12 flex justify-between'>
        <h1 className='font-courierBold text-xl text-black dark:text-white'>
          <Link className='hover:text-gray-500' href="/">&gt; Jan Arvik</Link>
        </h1>
        <ul className='flex items-center'>
          <li>
            <WiMoonAltThirdQuarter onClick={() => setDarkMode(!darkMode)} 
            className='cursor-pointer text-2xl dark:text-white'/>
          </li>
        </ul>
      </nav>
    </section>
    </main>
    </div>
    )
}